version: '1'
services:
  logic:
    image: docker.io/giuliotripi/parkmanagerservice:1.0
    ## image: virtualrobotdisi:2.0
    ports:
      - 8050:8050
    network_mode: host
  webapp:
    image: docker.io/giuliotripi/parkmanagerservice-webapp:1.0
    ##image: basicrobot21virtual:1.0
    ports:
      - 8081:8081/tcp
    depends_on:
      - logic
    network_mode: host

## -------------------------------------------------------------
## See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f basicrobotVirtual.yaml up
## docker-compose run --service-ports wenv
## docker-compose run --service-ports robot  ATTIVA ANCHE wenv