/* Generated by AN DISI Unibo */ 
package it.unibo.thermometer

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Thermometer ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var TEMP = 0.0; var OLDTEMP=0.0; var simulate: Boolean = false;  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('config.pl')","") //set resVar	
						solve("simulate(X)","") //set resVar	
						println(currentSolution)
						 val x = getCurSol("X").toString() 
								   simulate = ( x == "on")
						println("Thermometer init simulate=$simulate")
					}
					 transition( edgeName="goto",targetState="check", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_idle", 
							scope, context!!, "local_tout_thermometer_idle", 60000.toLong() )
					}
					 transition(edgeName="t00",targetState="check",cond=whenTimeout("local_tout_thermometer_idle"))   
					transition(edgeName="t01",targetState="handleRequest",cond=whenRequest("getValue"))
					transition(edgeName="t02",targetState="handleSetValue",cond=whenDispatch("setValue"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						
								   if(!simulate) {
										val p  = Runtime.getRuntime().exec("python3 thermometer.py")
										val reader = java.io.BufferedReader(java.io.InputStreamReader(p.getInputStream()))
										val line = reader.readLine()
										if(line != null)
											TEMP = line.toDouble()
									}
						answer("getValue", "sensorValue", "sensorValue($TEMP,temperature)"   )  
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleSetValue") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sensorValue(VALUE,SENSORNAME)"), Term.createTerm("sensorValue(TEMP,temperature)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												if(simulate) {
													TEMP = payloadArg(0).toDouble()
													//if equal to threshold is under
													if(TEMP > eu.musarellatripi.sensors.Values.TMAX &&
														OLDTEMP <= eu.musarellatripi.sensors.Values.TMAX
													) {
								emit("aboveTMAX", "aboveTMAX($TEMP)" ) 
								
													} else if(TEMP <= eu.musarellatripi.sensors.Values.TMAX &&
														OLDTEMP > eu.musarellatripi.sensors.Values.TMAX
													) {
								emit("underTMAX", "unserTMAX($TEMP)" ) 
								
													}
													OLDTEMP = TEMP
												}
						}
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("check") { //this:State
					action { //it:State
						
									if(!simulate) {
										val p  = Runtime.getRuntime().exec("python3 thermometer.py")
										val reader = java.io.BufferedReader(java.io.InputStreamReader(p.getInputStream()))
										val line = reader.readLine()
										if(line != null)
											TEMP = line.toDouble()
										if(TEMP > eu.musarellatripi.sensors.Values.TMAX &&
											OLDTEMP <= eu.musarellatripi.sensors.Values.TMAX
										) {
						emit("aboveTMAX", "aboveTMAX($TEMP)" ) 
						
										} else if(TEMP <= eu.musarellatripi.sensors.Values.TMAX &&
											OLDTEMP > eu.musarellatripi.sensors.Values.TMAX
										) {
						emit("underTMAX", "unserTMAX($TEMP)" ) 
						
										}
										OLDTEMP = TEMP
									}
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
