/* Generated by AN DISI Unibo */ 
package it.unibo.weight

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Weight ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var Numcheck = 0; var WEIGHT = 0  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Weight init")
						updateResourceRep( "init"  
						)
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_idle", 
							scope, context!!, "local_tout_weight_idle", 20000.toLong() )
					}
					 transition(edgeName="t067",targetState="check",cond=whenTimeout("local_tout_weight_idle"))   
					transition(edgeName="t068",targetState="handleRequest",cond=whenRequest("getValue"))
					transition(edgeName="t069",targetState="handleSetWeight",cond=whenDispatch("setValue"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						answer("getValue", "sensorValue", "sensorValue($WEIGHT,weight)"   )  
						println("[WEIGHT] value is $WEIGHT")
						updateResourceRep( "req"  
						)
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("check") { //this:State
					action { //it:State
						 Numcheck++  
						updateResourceRep( "check $Numcheck"  
						)
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleSetWeight") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sensorValue(VALUE,SENSORNAME)"), Term.createTerm("sensorValue(WEIGHT,weight)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 WEIGHT = payloadArg(0).toInt()  
								println("[WEIGHT] value is NOW $WEIGHT")
								updateResourceRep( "new w is $WEIGHT"  
								)
						}
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
