/* Generated by AN DISI Unibo */ 
package it.unibo.dtfree

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Dtfree ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "idle"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
					}
					 transition(edgeName="t057",targetState="timing",cond=whenDispatch("startTimer"))
				}	 
				state("timing") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_timing", 
							scope, context!!, "local_tout_dtfree_timing", 60000.toLong() )
					}
					 transition(edgeName="t158",targetState="timeout",cond=whenTimeout("local_tout_dtfree_timing"))   
					transition(edgeName="t159",targetState="idle",cond=whenDispatch("stopTimer"))
					transition(edgeName="t160",targetState="idle",cond=whenEvent("outdoorAreaNowFree"))
				}	 
				state("timeout") { //this:State
					action { //it:State
						emit("timeout", "timeout(_)" ) 
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
