/* Generated by AN DISI Unibo */ 
package it.unibo.thermometerevent

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Thermometerevent ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var Status: Int = -1  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_s0", 
							scope, context!!, "local_tout_thermometerevent_s0", 1000.toLong() )
					}
					 transition(edgeName="t069",targetState="check",cond=whenTimeout("local_tout_thermometerevent_s0"))   
				}	 
				state("check") { //this:State
					action { //it:State
					}
				}	 
			}
		}
}
