/* Generated by AN DISI Unibo */ 
package it.unibo.manager

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Manager ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("managerGUI init")
					}
					 transition(edgeName="t024",targetState="timeout",cond=whenEvent("timeout"))
				}	 
				state("timeout") { //this:State
					action { //it:State
						println("TIMEOUT")
					}
				}	 
			}
		}
}
