/* Generated by AN DISI Unibo */ 
package it.unibo.trolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Trolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var State = "idle"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						updateResourceRep( "idle"  
						)
						
									State = "idle"
					}
					 transition(edgeName="t025",targetState="stopped",cond=whenDispatch("stopTrolley"))
					transition(edgeName="t026",targetState="moveToIn",cond=whenRequest("moveToIn"))
					transition(edgeName="t027",targetState="moveToSlotIn",cond=whenRequest("moveToSlotIn"))
					transition(edgeName="t028",targetState="backHome",cond=whenRequest("backHome"))
					transition(edgeName="t029",targetState="moveToSlotOut",cond=whenRequest("moveToSlotOut"))
					transition(edgeName="t030",targetState="moveToOut",cond=whenRequest("moveToOut"))
				}	 
				state("moveToIn") { //this:State
					action { //it:State
						updateResourceRep( "working"  
						)
						delay(2000) 
						println("[TROLLEY] moveToIn1")
						answer("moveToIn", "moveDone", "moveDone(moveToIn,1)"   )  
					}
					 transition(edgeName="t131",targetState="stopped",cond=whenDispatch("stopTrolley"))
					transition(edgeName="t132",targetState="moveToIn",cond=whenRequest("moveToIn"))
					transition(edgeName="t133",targetState="moveToSlotIn",cond=whenRequest("moveToSlotIn"))
					transition(edgeName="t134",targetState="backHome",cond=whenRequest("backHome"))
					transition(edgeName="t135",targetState="moveToSlotOut",cond=whenRequest("moveToSlotOut"))
					transition(edgeName="t136",targetState="moveToOut",cond=whenRequest("moveToOut"))
				}	 
				state("moveToSlotIn") { //this:State
					action { //it:State
						updateResourceRep( "working"  
						)
						delay(2000) 
						println("[TROLLEY] moveToSlotIn2")
						answer("moveToSlotIn", "moveDone", "moveDone(moveToSlotIn,1)"   )  
					}
					 transition(edgeName="t237",targetState="stopped",cond=whenDispatch("stopTrolley"))
					transition(edgeName="t238",targetState="moveToIn",cond=whenRequest("moveToIn"))
					transition(edgeName="t239",targetState="moveToSlotIn",cond=whenRequest("moveToSlotIn"))
					transition(edgeName="t240",targetState="backHome",cond=whenRequest("backHome"))
					transition(edgeName="t241",targetState="moveToSlotOut",cond=whenRequest("moveToSlotOut"))
					transition(edgeName="t242",targetState="moveToOut",cond=whenRequest("moveToOut"))
				}	 
				state("backHome") { //this:State
					action { //it:State
						updateResourceRep( "working"  
						)
						delay(2000) 
						println("[TROLLEY] backHome3-6")
						answer("backHome", "moveDone", "moveDone(backHome,1)"   )  
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("moveToSlotOut") { //this:State
					action { //it:State
						updateResourceRep( "working"  
						)
						delay(2000) 
						println("[TROLLEY] moveToSlotOut4")
						answer("moveToSlotOut", "moveDone", "moveDone(moveToSlotOut,1)"   )  
					}
					 transition(edgeName="t343",targetState="stopped",cond=whenDispatch("stopTrolley"))
					transition(edgeName="t344",targetState="moveToIn",cond=whenRequest("moveToIn"))
					transition(edgeName="t345",targetState="moveToSlotIn",cond=whenRequest("moveToSlotIn"))
					transition(edgeName="t346",targetState="backHome",cond=whenRequest("backHome"))
					transition(edgeName="t347",targetState="moveToSlotOut",cond=whenRequest("moveToSlotOut"))
					transition(edgeName="t348",targetState="moveToOut",cond=whenRequest("moveToOut"))
				}	 
				state("moveToOut") { //this:State
					action { //it:State
						updateResourceRep( "working"  
						)
						delay(2000) 
						println("[TROLLEY] moveToOut5")
						answer("moveToOut", "moveDone", "moveDone(moveToOut,1)"   )  
					}
					 transition(edgeName="t449",targetState="stopped",cond=whenDispatch("stopTrolley"))
					transition(edgeName="t450",targetState="moveToIn",cond=whenRequest("moveToIn"))
					transition(edgeName="t451",targetState="moveToSlotIn",cond=whenRequest("moveToSlotIn"))
					transition(edgeName="t452",targetState="backHome",cond=whenRequest("backHome"))
					transition(edgeName="t453",targetState="moveToSlotOut",cond=whenRequest("moveToSlotOut"))
					transition(edgeName="t454",targetState="moveToOut",cond=whenRequest("moveToOut"))
				}	 
				state("stopped") { //this:State
					action { //it:State
						updateResourceRep( "stopped"  
						)
						println("[TROLLEY] stopped")
						discardMessages = true
					}
					 transition(edgeName="t555",targetState="idle",cond=whenDispatch("resumeTrolley"))
				}	 
			}
		}
}
