name: Docker image update
on:
  push:
    branches:
      - master
jobs:
  push_to_registry_core:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build_core
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: giuliotripi/parkmanagerservice:github-1.0
          context: .
          file: sprint4/core/Dockerfile
  push_to_registry_web:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build_web
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: giuliotripi/parkmanagerservice-webapp:github-1.0
          context: .
          file: sprint4/web/Dockerfile
